Repository mgkkm/meerkats-frontend, pull requests merged in 2023-05, with the labels that each got.

#1 [Feat] header scroll 기능 구현 완료
  src/App.tsx
  src/components/ContentContainer/ContentContainer.tsx
  src/components/Nav/Nav.tsx
  src/components/Nav/components/SideBar.tsx
Labels: 코드리뷰요청, 리뷰수정완료, 린갱

#3 [Layout] footer 구현 완료
  src/components/Footer/Footer.tsx
Labels: 코드리뷰요청, 린갱

#6 [Feat] 토글 및 카운터 상태 관리 기능 구현
  src/recoil/NumberState.tsx
  src/recoil/ToggleState.tsx
Labels: 러윤

#14 [Feat] pageY로 스크롤 위치 감지 후 탑버튼 보여주기 기능 구현 완료
  src/App.tsx
  src/components/ContentContainer/ContentContainer.tsx
  src/components/TopButton/TopBtn.tsx
  src/recoil/TopBtnState.tsx
Labels: 린갱, 코드리뷰완료

#11 [Feat] 블로그 post 기능 구현 완료 (태그 같이 올라가는거 수정 예정)
  package-lock.json
  package.json
  src/Router.tsx
  src/pages/Blog/BlogPosting.tsx
  src/pages/Blog/components/Category.tsx
  src/pages/Blog/components/CustomEditor.tsx
  src/pages/Blog/components/PostBtn.tsx
  src/pages/Blog/components/Title.tsx
  src/recoil/BlogPostState.tsx
Labels: 구현중, 린갱

#13 [Add] 네이버 로그인 버튼 레이아웃 추가
  public/images/Login/logo_naver.png
  src/pages/Login/Login.tsx
  src/pages/Login/components/NaverLoginBtn.tsx
Labels: 구현중, 앙두

#15 [Feat] LikeScrapBtn 기능 구현
  src/components/LikeScrapBtn/LikeScrapBtn.tsx
Labels: 러윤, 코드리뷰완료

#7 [Feat] 이벤트 -> 이벤트 디테일 페이지 이동 기능 구현 완료 / mock데이터로 통신 완료
  public/data/data.json
  public/data/eventInfo.json
  src/Router.tsx
  src/pages/Event/EventDetail.tsx
  src/pages/Event/EventList.tsx
  src/pages/Event/components/EmailInput.tsx
  src/pages/Event/components/EventInfo.tsx
  src/pages/Event/components/EventSchedule.tsx
  src/pages/Event/components/MovieInfo.tsx
  src/pages/Event/components/Pagenation.tsx
Labels: 구현중, 린갱, 코드리뷰완료

#23 [Feat] 영화 포스터 선택시 해당 영화상세 페이지로 이동 / hover시 영화상세 이동 위해 컴포넌트 분리 완료
  public/images/Main/main_poster_1.jpeg
  public/images/Main/main_poster_2.jpeg
  src/index.css
  src/pages/Main/Main.tsx
  src/pages/Main/components/MainCarousel.tsx
  src/pages/Main/components/MainTab.tsx
  src/pages/Main/components/MainTopRankCarousel.tsx
  src/pages/Main/components/TabItems.tsx
  src/pages/Main/components/TopRankItems.tsx
  src/recoil/MainDataState.tsx
Labels: 구현중, 코드리뷰요청, 린갱

#10 [Feat] comment component 구현 완료 (통신 수정 필요)
  src/App.tsx
  src/components/Comment/Comments.tsx
  src/components/Comment/components/CommentInput.tsx
  src/components/Comment/components/DropDownBtn.tsx
  src/recoil/BlogPostState.tsx
  src/recoil/Jwt.tsx
Labels: 구현중, 린갱

#25 [Feat] 댓글 레이아웃 구현
  src/components/Comment/components/CommentInput.tsx
  src/components/Comment/components/CommentList.tsx
  src/components/Comment/components/DropDownBtn.tsx
  src/recoil/CommentState.tsx
  src/recoil/Jwt.tsx
Labels: 러윤, 코드리뷰완료

#24 [Feat] 블로그 디테일 페이지 레이아웃 구현
  package-lock.json
  package.json
  src/App.tsx
  src/Router.tsx
  src/components/CreatedAt/CreatedAt.tsx
  src/pages/Blog/BlogDetail/BlogDetail.tsx
  src/pages/Blog/BlogDetail/components/BlogContent.tsx
  src/pages/Blog/BlogDetail/components/BlogFooter.tsx
  src/pages/Blog/BlogDetail/components/BlogHeader.tsx
  src/recoil/BlogDetailState.tsx
  src/recoil/TokenState.tsx
Labels: 코드리뷰요청, 러윤

#16 [ Feat] 회원가입 페이지 이메일 인증기능 구현
  src/Router.tsx
  src/pages/Signin/Signin.tsx
  src/pages/Signin/components/EmailInput.tsx
  src/recoil/UserInputState.tsx
Labels: 구현중, 앙두, 코드리뷰완료

#19 [ Feat] 블로그 메인 무한 스크롤 기능 구현 / 조건부 렌더링 기능 구현
  public/images/Blog/BlogMain/dropdown_arrow.png
  public/images/blog/blogMain/blog_test.jpeg
  public/images/blog/blogMain/heart.png
  src/Router.tsx
  src/components/CreatedAt/CreatedAt.tsx
  src/index.css
  src/pages/Blog/BlogMain.tsx
  src/pages/Blog/components/BlogMain/BlogArticle.tsx
  src/pages/Blog/components/BlogMain/BlogDropDown.tsx
  src/pages/Blog/components/BlogMain/BlogMainTop.tsx
  src/pages/Blog/components/BlogMain/BlogRenderArticle.tsx
  src/pages/Blog/components/BlogMain/BlogScrollArticle.tsx
  src/pages/Blog/components/BlogMain/BlogSearchArticle.tsx
  src/pages/Blog/components/BlogMain/BlogSpoToggle.tsx
  src/pages/Blog/components/BlogMain/Search.tsx
  src/pages/Blog/components/BlogMain/SearchModal.tsx
  src/recoil/ArticleDataState.tsx
  src/recoil/SearchDataState.tsx
Labels: 구현중, 앙두, 코드리뷰완료

#22 [Feat] 구독 페이지 레이아웃 구현
  public/images/membership/membership1.jpg
  public/images/membership/membership2.jpg
  public/images/membership/membership3.jpg
  src/Router.tsx
  src/pages/Subscribe/Subscribe.tsx
  src/pages/Subscribe/components/Option.tsx
  src/pages/Subscribe/components/Payment.tsx
  src/pages/Subscribe/components/Terms.tsx
Labels: 러윤, 코드리뷰완료

#28 [Feat] MovieDetailHeader 레이아웃 및 기능 구현
  public/images/movieDetail/movie1.svg
  public/images/movieDetail/movie2.svg
  public/images/movieDetail/movie3.svg
  public/images/movieDetail/movie4.svg
  src/pages/MovieDetail/components/MovieDetailHeader.tsx
Labels: 러윤, 코드리뷰완료

#29 [Feat] MoviePlayer 기능 및 영화 디테일 페이지 레이아웃 구현
  src/Router.tsx
  src/pages/MovieDetail/MovieDetail.tsx
  src/pages/MovieDetail/components/MovieDetailTab.tsx
  src/pages/MovieDetail/components/MoviePlayer.tsx
  src/pages/MovieDetail/components/TrailerPlaylist.tsx
  src/recoil/MovieDetailState.tsx
Labels: 러윤, 코드리뷰완료

#30 [Feat] TrailerPlaylist 및 ModalPlayer 기능 구현
  src/pages/MovieDetail/components/ModalPlayer.tsx
  src/pages/MovieDetail/components/RelatedVideo.tsx
  src/pages/MovieDetail/components/TrailerPlaylist.tsx
Labels: 러윤, 코드리뷰완료

#20 [Fix] nav 수정사항 반영
  src/components/Nav/Nav.tsx
  src/components/Nav/components/Search.tsx
  src/components/Nav/components/SearchModal.tsx
  src/components/Nav/components/SideBar.tsx
Labels: 구현 완료, 앙두, 코드리뷰완료

#32 [Feat] MovieTab 및 MovieDetailBlog 기능 구현
  src/pages/MovieDetail/components/MovieDetailBlog.tsx
  src/pages/MovieDetail/components/MovieDetailBlogCard.tsx
  src/pages/MovieDetail/components/MovieDetailTab.tsx
Labels: 러윤, 코드리뷰완료

#34 [Feat] MovieChat 기능 구현
  src/pages/MovieDetail/components/MovieChat.tsx
Labels: 러윤, 코드리뷰완료

#21 [Feat] 자체 로그인 구현 완료 / 구글 소셜 로그인 구현중
  public/images/Login/logo_google.png
  src/pages/Login/Login.tsx
  src/pages/Login/components/GoogleLoginBtn.tsx
  src/pages/Login/components/UserForm.tsx
  src/pages/Login/components/UserInput.tsx
  src/recoil/InputValueState.tsx
Labels: 구현중, 앙두, 코드리뷰완료

#43 [Fix] 블로그 페이지 / 영화 상세 페이지 일때 요청 다르게 구현 완료
  src/components/Comment/components/CommentInput.tsx
  src/components/Comment/components/DropDownBtn.tsx
  src/components/ContentContainer/ContentContainer.tsx
Labels: 구현 완료, 린갱

#44 [Fix] DecodeToken 함수 적용
  src/pages/Blog/BlogDetail/BlogDetail.tsx
  src/pages/Blog/BlogDetail/components/BlogHeader.tsx
Labels: 러윤

#45 [Fix] 로그인 수정사항 반영
  src/pages/Login/components/KakaoLogin.tsx
  src/pages/Login/components/UserForm.tsx
  src/pages/Login/components/UserInput.tsx
Labels: 구현 완료, 앙두

#41 [Fix] 글 등록시 필수 항목 비어있으면 등록 불가능하게 에러 핸들링 ( 썸네일 이미지 수정 필요 )
  src/pages/Blog/BlogDetail/components/BlogHeader.tsx
  src/pages/Blog/BlogPosting/components/PostBtn.tsx
  src/recoil/BlogPostState.tsx
Labels: 구현중, 린갱

#47 [Fix] nav 수정사항 반영
  public/images/blogThumbnail.jpg
  src/components/Nav/components/Search.tsx
  src/components/Nav/components/SearchModal.tsx
  src/recoil/SearchDataState.tsx
Labels: 구현 완료, 앙두

#42 [Feat] CopyBtn 기능 구현
  src/components/Alert/Modal.tsx
  src/components/CopyBtn/CopyBtn.tsx
  src/pages/MovieDetail/components/MovieDetailHeader.tsx
Labels: 러윤

#40 [Fix] 영화 디테일 페이지 버그 수정
  src/pages/MovieDetail/MovieDetail.tsx
  src/pages/MovieDetail/components/ModalPlayer.tsx
  src/pages/MovieDetail/components/MovieChat.tsx
  src/pages/MovieDetail/components/MovieDetailBlog.tsx
  src/pages/MovieDetail/components/MovieDetailBlogCard.tsx
  src/pages/MovieDetail/components/MovieDetailHeader.tsx
  src/pages/MovieDetail/components/TrailerPlaylist.tsx
Labels: 구현중, 러윤

#48 [Fix] 블로그 메인 수정사항 반영
  src/pages/Blog/BlogMain.tsx
  src/pages/Blog/components/BlogMain/BlogArticle.tsx
  src/pages/Blog/components/BlogMain/BlogDropDown.tsx
  src/pages/Blog/components/BlogMain/BlogMainTop.tsx
Labels: 구현중, 앙두

#49 [Feat] 결제 기능 구현
  src/components/Alert/Modal.tsx
  src/components/DecodeToken/DecodeToken.tsx
  src/pages/Membership/components/MembershipCard.tsx
  src/pages/Subscribe/Subscribe.tsx
  src/pages/Subscribe/components/PaymentInfo.tsx
  src/pages/Subscribe/components/PaymentInput.tsx
  src/pages/Subscribe/components/SubscribeBtn.tsx
  src/pages/Subscribe/components/Terms.tsx
  src/recoil/PaymentState.tsx
Labels: 러윤

#50 [Fix] LikeScrapBtn 토큰 및 alert 수정
  src/components/LikeScrapBtn/LikeScrapBtn.tsx
  src/pages/MovieDetail/components/MoviePlayer.tsx
  src/pages/MovieDetail/components/RelatedVideo.tsx
  src/recoil/MovieDetailState.tsx
Labels: 러윤

#56 [Fix] 영화 디테일 페이지 블로그 데이터 및 반응형 수정
  src/components/Comment/components/CommentList.tsx
  src/pages/MovieDetail/MovieDetail.tsx
  src/pages/MovieDetail/components/MovieDetailBlog.tsx
  src/pages/MovieDetail/components/MovieDetailBlogCard.tsx
  tailwind.config.js
Labels: 러윤

#61 [Fix] 블로그 메인페이지 My blog 조건부 렌더링 구현
  src/pages/Blog/BlogMain/components/BlogArticle.tsx
  src/pages/Blog/BlogMain/components/BlogMainTop.tsx
  src/pages/Blog/BlogMain/components/BlogRenderArticle.tsx
  src/pages/Blog/BlogMain/components/BlogScrollArticle.tsx
  src/pages/Blog/BlogMain/components/BlogSearchArticle.tsx
  src/pages/Blog/BlogMain/components/BlogSpoToggle.tsx
  src/recoil/ArticleDataState.tsx
Labels: 구현 완료, 앙두

#59 [Feat] 구독 페이지 반응형 수정
  src/components/ContentContainer/ContentContainer.tsx
  src/pages/Main/components/MainCarousel.tsx
  src/pages/Subscribe/Subscribe.tsx
  src/pages/Subscribe/components/Option.tsx
  src/pages/Subscribe/components/PaymentInfo.tsx
  src/pages/Subscribe/components/PaymentInput.tsx
  src/pages/Subscribe/components/Terms.tsx
Labels: 러윤

#60 [Fix] 영화 디테일 페이지 버그 수정 및 리팩토링
  src/pages/MovieDetail/MovieDetail.tsx
  src/pages/MovieDetail/components/MovieChat.tsx
  src/pages/MovieDetail/components/MovieDetailBlogCard.tsx
  src/pages/MovieDetail/components/MovieDetailHeader.tsx
  src/recoil/MovieDetailState.tsx
Labels: 러윤

#67 [Fix] 검색창 중복 클릭 시, 여닫아 지는 문제 수정
  src/components/Nav/components/Search.tsx
  src/components/Nav/components/SearchModal.tsx
  src/pages/Blog/BlogMain/components/Search.tsx
  src/pages/Blog/BlogMain/components/SearchModal.tsx
  src/recoil/SearchState.tsx
Labels: 앙두

#68 [Fix] 좋아요 카운터 및 하트 상태 연결
  src/pages/Blog/BlogMain/components/BlogArticle.tsx
  src/pages/Blog/BlogMain/components/BlogRenderArticle.tsx
  src/pages/Blog/BlogMain/components/BlogScrollArticle.tsx
  src/pages/Blog/BlogMain/components/BlogSearchArticle.tsx
Labels: 앙두

#70 [Feat] PaymentInput 유효성 검사 기능 구현
  src/pages/MovieDetail/components/MovieChat.tsx
  src/pages/Subscribe/components/PaymentInfo.tsx
  src/pages/Subscribe/components/PaymentInput.tsx
  src/pages/Subscribe/components/SubscribeBtn.tsx
  src/pages/Subscribe/components/Terms.tsx
  src/recoil/PaymentState.tsx
Labels: 러윤

#72 [Fix] LikeScrapBtn 버그 수정 (BlogDetail 에서 reset 후 데이터 저장)
  src/pages/Blog/BlogDetail/BlogDetail.tsx
Labels: 러윤
